### PR TITLE
Automatically start ex_cldr application

### PR DESCRIPTION
**Pull request by dolfinus**
If one starts application without ex_cldr, like iex console, log will be full or warnings like:
```
warning: Cldr.Number.PluralRule.Transformer.rules_to_condition_statement/2 defined in application :ex_cldr is used by the current application but the current application does not directly depend on :ex_cldr. To fix this, you must do one of:

  1. If :ex_cldr is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :ex_cldr is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :ex_cldr, you may optionally skip this warning by adding [xref: [exclude: Cldr.Number.PluralRule.Transformer] to your "def project" in mix.exs

Found at 2 locations:
  lib/linguist/cldr_backend.ex:1: Linguist.Cldr.Number.Cardinal
  lib/linguist/cldr_backend.ex:1: Linguist.Cldr.Number.Ordinal
```

Here I've added explicit ex_cldr application starting.

### CODE REVIEW

**Comment by dolfinus** [comment]
After upgrading ex_cldr to 2.18 warning is being replaced with an error which prevents library from compilation. So it is a critical patch.

**Comment by dolfinus** [comment]
@mertonium Could you please take a look at this?

**Comment by dolfinus** [comment]
@mertonium What do you think about this PR?

**Comment by dolfinus** [comment]
@mertonium @maur1th @quaelin Anyone?

**Comment by maur1th** [comment]
@koozdra Can you have a look?

**Review by mertonium — APPROVED** [review]
LGTM

**Comment by dolfinus** [comment]
Thanks!

**Pull request merged**
